### ISSUE TITLE
Possible to view Model markdowns?

### ISSUE THREAD

**Issue by fnbillimoria** [Energy-MAC/LITS.jl#55]
What is the best way to view the inverter model markdown files in github?  In particular the following: 
https://github.com/Energy-MAC/LITS.jl/blob/master/docs/src/Models/inverters.md.  I would like to view the formulas for the components of the model but for some reason the inline equations do not show up.  Is there any preferred way to view the markdown equations? 

Many thanks
Farhad

**Comment by jd-lara** [comment]
@fnbillimoria the details of the inverter component models as currently implemented can be found in the documentation https://energy-mac.github.io/LITS.jl/latest/Models/inverters/ 

The names are a bit outdated, we are working on a new release with more modeling capabilities soon.

**Comment by fnbillimoria** [comment]
Thank you Jose!
